version: '3.8'

services:
  queue:
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commerce-platform-orders
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
    ports:
      - "3310:3306"
    volumes:
      - mysql_data_container:/data/db

volumes:
  mysql_data_container:
  rabbitmq_container:

networks:
  default:
    driver: bridge